# Generated by Django 3.1.10 on 2021-05-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.TextField(max_length=20)),
                ('date', models.DateField(verbose_name='')),
                ('open', models.DecimalField(decimal_places=6, max_digits=20)),
                ('high', models.DecimalField(decimal_places=6, max_digits=20)),
                ('low', models.DecimalField(decimal_places=6, max_digits=20)),
                ('close', models.DecimalField(decimal_places=6, max_digits=20)),
                ('adj_close', models.DecimalField(decimal_places=6, max_digits=20)),
                ('volume', models.IntegerField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
